package com.miracl.trust.storage.room.model

import androidx.room.Entity

@Entity(tableName = "users", primaryKeys = ["userId", "projectId"])
internal data class UserModel(
    val userId: String,
    val projectId: String,
    val revoked: Boolean,
    val pinLength: Int,
    val mpinId: ByteArray,
    val token: ByteArray,
    val dtas: String,
    val publicKey: ByteArray?
) {
    // AUTOGENERATED
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as UserModel

        if (userId != other.userId) return false
        if (projectId != other.projectId) return false
        if (revoked != other.revoked) return false
        if (pinLength != other.pinLength) return false
        if (!mpinId.contentEquals(other.mpinId)) return false
        if (!token.contentEquals(other.token)) return false
        if (dtas != other.dtas) return false
        if (publicKey != null) {
            if (other.publicKey == null) return false
            if (!publicKey.contentEquals(other.publicKey)) return false
        } else if (other.publicKey != null) return false

        return true
    }

    // AUTOGENERATED
    override fun hashCode(): Int {
        var result = userId.hashCode()
        result = 31 * result + projectId.hashCode()
        result = 31 * result + revoked.hashCode()
        result = 31 * result + pinLength
        result = 31 * result + mpinId.contentHashCode()
        result = 31 * result + token.contentHashCode()
        result = 31 * result + dtas.hashCode()
        result = 31 * result + (publicKey?.contentHashCode() ?: 0)
        return result
    }
}