name: CI
on:
  push:
    branches:
      - '*'
env:
    JAVA_VERSION: 17
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v4
      
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: ${{ env.JAVA_VERSION }}
            cache: gradle

      - name: Check Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.5'

      - name: Check lint
        run: ./gradlew lint

      - name: Check binary compatibility
        run: ./gradlew apiCheck || { exit_code=$?; printf "*** This PR changes MIRACL Trust's public API. If this change is intentional, run './gradlew apiDump' and commit the new API files. ***"; exit $exit_code; }
      
      - name: Lint README.md
        run: |
            npm install -g markdownlint-cli
            markdownlint README.md
  
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v4
      
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: ${{ env.JAVA_VERSION }}
            cache: gradle

      - name: Check Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Run unit tests
        run: ./gradlew :miracl-sdk:testDebugUnitTest

  instrumentation-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v4
      
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: ${{ env.JAVA_VERSION }}
            cache: gradle

      - name: Check Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      -  name: Enable KVM
         run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Grant execute permission for instrumentation tests script
        run: chmod +x run-instrumentation-tests.sh

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        env: 
          TEST_BASE_URL: ${{ vars.TEST_BASE_URL }}
          TEST_CUV_CLIENT_SECRET: ${{ secrets.TEST_CUV_CLIENT_SECRET }}
          TEST_CUV_CLIENT_ID: ${{ vars.TEST_CUV_CLIENT_ID }}
          TEST_CUV_PROJECT_ID: ${{ vars.TEST_CUV_PROJECT_ID }}
          TEST_CUV_PROJECT_URL: ${{ vars.TEST_CUV_PROJECT_URL }}
          TEST_DV_PROJECT_ID: ${{ vars.TEST_DV_PROJECT_ID }}
          TEST_DV_PROJECT_URL: ${{ vars.TEST_DV_PROJECT_URL }}
          TEST_ECV_PROJECT_ID: ${{ vars.TEST_ECV_PROJECT_ID }}
          TEST_ECV_PROJECT_URL: ${{ vars.TEST_ECV_PROJECT_URL }}
          GMAIL_CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}
          GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}
        with:
          api-level: 35
          arch: "x86_64"
          cmake: "3.30.5"
          script: ./run-instrumentation-tests.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: IntegrationTests-report
          path: miracl-sdk/build/reports